version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nt-cfo-api
    restart: always
    ports:
      - "0.0.0.0:3002:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
